Refactor Theme Setup
Signify-epfl/signify-app pull request #140
Opened 2024-10-28 20:55 UTC by ziyadbagh

### Pull Request Details:

### 1. **Implemented Light Theme with Centralized Colors**:
   - Set up a light color scheme using `colors.xml` to define primary and secondary colors (blue and white).
   - Removed any previously hardcoded colors in the theme, ensuring that all colors are managed through `colors.xml` for consistency and easier updates.

### 2. **Refactored `SignifyTheme` with Light Mode Focus, Keeping Dark Mode for Future Implementation**:
   - Simplified `SignifyTheme` to focus on light mode based on current project requirements, while keeping the dark mode structure in place for future feature implementation.
   - Updated `SignifyTheme` to directly reference colors from `colors.xml`.

### 3. **Removed Hardcoded Colors**:
   - Deleted previous hardcoded colors to streamline color management, ensuring all colors now come from `colors.xml`.

### 5. **Added UI Tests for Theme Colors**:
   - Implemented UI tests to verify that components using `MaterialTheme.colorScheme.primary` and `MaterialTheme.colorScheme.secondary` display as expected, ensuring accurate theme color application.
   - Used `testTag` markers on components for efficient testing, verifying theme usage without direct color comparison.

### 6. **Unit Tests for Typography Properties**:
   - Added a unit test to confirm that `Typography.bodyLarge` has the correct font weight, font size, line height, and letter spacing.
   - These tests help maintain consistency in text styling, catching any unintended typography changes.

This pull request enhances code organization, improves maintainability, and ensures a consistent app appearance by centralizing theme and typography settings , and modestly improving test coverage by **2%**.
The dark mode setup remains in the codebase for future feature implementation.

![image](https://github.com/user-attachments/assets/04d4f0c0-8b29-4929-ad7a-50d09b30886c)

2024-10-29 11:42 UTC, SaFouNaldo approved these changes
Nice improvements! 👍 Noted that you've added:

- ThemeTest and TypeTest to enhance test coverage

2024-10-30 12:29 UTC, nada-ezziti approved these changes
I've reviewed the theme refactor, and the setup is clean, efficient, and ready for future dark mode expansion. The centralization of colors in colors.xml enhances consistency and maintainability. I also appreciate the thoughtful approach to testing theme colors and typography, which will help maintain design integrity as we add more features.

**Code Highlights:**
The test cases for primary and secondary color checks (VerifyPrimaryAndSecondaryColors) and typography validation (testBodyLargeTypographyProperties) ensure that our UI and text styles follow the design requirements precisely. These tests strengthen theme implementation and highlight focus on consistent styling across the app.

Approved and ready to merge!

2024-10-30 14:53 UTC, ThomasMPont requested changes
SonarCloud raises 2 small issues from this PR. I'll fix them real quick.

2024-10-30 15:03 UTC, ThomasMPont approved these changes

2024-10-30 16:31 UTC, merged