Address sonarcloud issues on UI code
Signify-epfl/signify-app pull request #154
Opened 2024-10-31 16:20 UTC by ThomasMPont

Since I've only addressed code warnings, this should be a simple PR to review.

I've gone over the remaining SonarCloud issues on UI source code, hoping all of them go away.
None of these refactors should meaningfully alter the product.

2024-10-31 18:48 UTC, ziyadbagh approved these changes
This looks straightforward—approved!

2024-11-01 01:27 UTC, ziyadbagh requested changes
Please fix this unresolved reference :
file:///home/runner/work/signify-app/signify-app/app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt:149:28 Unresolved reference: verticalScroll

2024-11-01 07:14 UTC, ThomasMPont commented
> Please fix this unresolved reference : file:///home/runner/work/signify-app/signify-app/app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt:149:28 Unresolved reference: verticalScroll

I've fixed it.
This was simply a missing import from a bad small merge I tried doing through Github. With small changes like this, feel free to commit the fix yourself when I'm not there, it could save a lot of time.

2024-11-01 18:35 UTC, ziyadbagh approved these changes

2024-11-02 22:48 UTC, merged