feat: add end2end tests for practice epic
Signify-epfl/signify-app pull request #260
Opened 2024-11-21 10:06 UTC by SaFouNaldo

2024-11-22 22:59 UTC, NBCCF025 requested changes
#### Overview
This PR demonstrates significant progress by addressing dependency issues, introducing an offline mode, and creating the first end-to-end test for the app. The changes are well-documented and provide a solid foundation for future improvements.

---

#### **End To End Test**
- The first end to end test is well implemented and correctly test the practice epic, but we should remind us that we used the offline mode for this one and bypass the login logic.

#### **Offline Mode Feature**
- This feature is great and provide the following result (images of the screens):

![login](https://github.com/user-attachments/assets/533aeec4-4201-4b1f-afaf-032889c4a4e0)
![ProfileChallenge](https://github.com/user-attachments/assets/f5616aea-6e86-46e2-966f-d6465c42a760)


---

#### **Requested Changes**
- The `isOfflineState` shouldn't be put as false just by clicking on the button to connect, it should be assigned only after a successful login.
- Offline mode need some changes. I currently tested it with and whitout internet connectivity, and I have seen the Following:
	1) (with internet connectivity):
		- The feedback are accessible, can be filled and can be send to the firebase repository as it doesn't require a connected user.
		- The quiz screen is accessible but doesn't show anything except the title and the back button, but I don't know why as the quizzes doesn't require a connected user and I have internet connectivity in this case to access the firebase repository.
		- The quest screen is accessible but doesn't show anything except the title and the back button as there is no connected user to access the `initialQuestAccessDate`.
	2) (without internet connectivity):
		- The feedback are accessible, can be filled but can't be send to the firebase repository (The last one is normal as I have no internet connectivity).
		- The quiz screen is accessible but doesn't show anything except the title and the back button as there is no internet connectivity to access the quiz repository.
		- The quest screen is accessible but doesn't show anything except the title and the back button as there is no connected user and no internet connectivity to access the firebase repository.
	- I suggest that this 3 screens (feedbackScreen, QuizScreen and QuestScreen) take a similar behaviour as ProfileScreen and ChallengeScreen for offline mode, so it requires the user to be connected.

![homeTop](https://github.com/user-attachments/assets/bfbeab81-da74-459d-9044-a8bd2db98716)
![feedback](https://github.com/user-attachments/assets/df4eed3f-2b33-4490-9b79-0626ba158231)
![firebaseFeedback](https://github.com/user-attachments/assets/faf043c6-3ddc-44f6-918a-ec2182e7d222)
![quiz](https://github.com/user-attachments/assets/5bcd18b8-8e3c-4f49-82fb-a729aaab0a95)
![quest](https://github.com/user-attachments/assets/0a09b330-c210-4c48-8d53-196bcd6d8cd6)


---

### Final Comments
This PR successfully addresses its purpose, but I recommand some changes before merging it.
Great work overall!

2024-11-22 22:59 UTC, NBCCF025 commented on app/src/main/java/com/github/se/signify/ui/screens/LoginScreen.kt
Is it necessary to have the following line "isOfflineState = false // Set offline state to false when signed in" both in line 72 and 136. Shouldn't it be set only when the authentication is complete (when the toast of a successful login is send) at line 72 ?

2024-11-22 23:14 UTC, SaFouNaldo commented
> #### Overview
> This PR demonstrates significant progress by addressing dependency issues, introducing an offline mode, and creating the first end-to-end test for the app. The changes are well-documented and provide a solid foundation for future improvements.
> 
> #### **End To End Test**
> * The first end to end test is well implemented and correctly test the practice epic, but we should remind us that we used the offline mode for this one and bypass the login logic.
> 
> #### **Offline Mode Feature**
> * This feature is great and provide the following result (images of the screens):
> 
> ![login](https://private-user-images.githubusercontent.com/93980621/389130894-533aeec4-4201-4b1f-afaf-032889c4a4e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMTcyNjIsIm5iZiI6MTczMjMxNjk2MiwicGF0aCI6Ii85Mzk4MDYyMS8zODkxMzA4OTQtNTMzYWVlYzQtNDIwMS00YjFmLWFmYWYtMDMyODg5YzRhNGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDIzMDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMWM0ZjViMWExNzc1NzRlM2EyNjlkNjE3MGMxNDg5MmYzYzM5ZjU0NzM4MmJjOTQ5MGZlNDE5YzU2NDZiNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wrJoWBmmQVVuHbn5JGgm4K3UuYdsh_I908SdfC6bPVQ) ![ProfileChallenge](https://private-user-images.githubusercontent.com/93980621/389130911-f5616aea-6e86-46e2-966f-d6465c42a760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMTcyNjIsIm5iZiI6MTczMjMxNjk2MiwicGF0aCI6Ii85Mzk4MDYyMS8zODkxMzA5MTEtZjU2MTZhZWEtNmU4Ni00NmUyLTk2NmYtZDY0NjVjNDJhNzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDIzMDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMTFlODU3YTA1MTJlZTdjNzYyNmEzYmZjZWZiZWNmMDEzZDgxMDA1YWY4MzQ3ZDAzOGM4NGYzMjhiZjRlNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kCvkFEyPNGnl7-hSxaiRwYAjC8xTr5MANAs4WxtAnnw)
> 
> #### **Requested Changes**
> * The `isOfflineState` shouldn't be put as false just by clicking on the button to connect, it should be assigned only after a successful login.
> * Offline mode need some changes. I currently tested it with and whitout internet connectivity, and I have seen the Following:
>   
>   1. (with internet connectivity):
>      
>      * The feedback are accessible, can be filled and can be send to the firebase repository as it doesn't require a connected user.
>      * The quiz screen is accessible but doesn't show anything except the title and the back button, but I don't know why as the quizzes doesn't require a connected user and I have internet connectivity in this case to access the firebase repository.
>      * The quest screen is accessible but doesn't show anything except the title and the back button as there is no connected user to access the `initialQuestAccessDate`.
>   2. (without internet connectivity):
>      
>      * The feedback are accessible, can be filled but can't be send to the firebase repository (The last one is normal as I have no internet connectivity).
>      * The quiz screen is accessible but doesn't show anything except the title and the back button as there is no internet connectivity to access the quiz repository.
>      * The quest screen is accessible but doesn't show anything except the title and the back button as there is no connected user and no internet connectivity to access the firebase repository.
>   
>   
>   * I suggest that this 3 screens (feedbackScreen, QuizScreen and QuestScreen) take a similar behaviour as ProfileScreen and ChallengeScreen for offline mode, so it requires the user to be connected.
> 
> ![homeTop](https://private-user-images.githubusercontent.com/93980621/389131138-bfbeab81-da74-459d-9044-a8bd2db98716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMTcyNjIsIm5iZiI6MTczMjMxNjk2MiwicGF0aCI6Ii85Mzk4MDYyMS8zODkxMzExMzgtYmZiZWFiODEtZGE3NC00NTlkLTkwNDQtYThiZDJkYjk4NzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDIzMDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNDg3MjMxYzUzMzBiYmQwNDkxYjFlMWU4NzFlOWEwNzAwYTAwOGQ5MzVmNGM0NDI2YTNlOTgyN2YyZDU2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K-lcBMKvdUcOm2wEBjak4wjD4zONjLVzaRkMRIIZggs) ![feedback](https://private-user-images.githubusercontent.com/93980621/389131171-df4eed3f-2b33-4490-9b79-0626ba158231.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMTcyNjIsIm5iZiI6MTczMjMxNjk2MiwicGF0aCI6Ii85Mzk4MDYyMS8zODkxMzExNzEtZGY0ZWVkM2YtMmIzMy00NDkwLTliNzktMDYyNmJhMTU4MjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDIzMDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiY2QxMTY5MTU5NWM4M2Q2NTRiYzUxMTBjODJjNzIxYjM1NDYzN2JmZWU0MDEyMDY5ZmIzMWZkOWNjZDE3YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DCll2Gw9prqZk5uX4LSm3JtNWZn86oMyipbGZ-ccH74) ![firebaseFeedback](https://private-user-images.githubusercontent.com/93980621/389131201-faf043c6-3ddc-44f6-918a-ec2182e7d222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMTcyNjIsIm5iZiI6MTczMjMxNjk2MiwicGF0aCI6Ii85Mzk4MDYyMS8zODkxMzEyMDEtZmFmMDQzYzYtM2RkYy00NGY2LTkxOGEtZWMyMTgyZTdkMjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDIzMDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNmUwMmE0ZWIzN2QxM2EyNGE3NDg4N2MyNjUyYzk0ZmY5MGMyYjUwYTA0ZmI5MWMzMjY0MDY0MWZkOTE3ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hMf9cu5CTBoenTB0zkCUiZf07JRLPbPAwb0L9Jj6_GM) ![quiz](https://private-user-images.githubusercontent.com/93980621/389131228-5bcd18b8-8e3c-4f49-82fb-a729aaab0a95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMTcyNjIsIm5iZiI6MTczMjMxNjk2MiwicGF0aCI6Ii85Mzk4MDYyMS8zODkxMzEyMjgtNWJjZDE4YjgtOGUzYy00ZjQ5LTgyZmItYTcyOWFhYWIwYTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDIzMDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjODA4NjFjY2NkYzkxYzFjNjA5Yzc3MzQwNWIyNWViMTZmM2IzOWU2ZWUzM2E3Y2U0MmVmZGY3OTI5Y2M3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v_zEeOziDHxNaccobfJAvh_Cjs9YcORvqb5sUixlA4U) ![quest](https://private-user-images.githubusercontent.com/93980621/389131236-0a09b330-c210-4c48-8d53-196bcd6d8cd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMTcyNjIsIm5iZiI6MTczMjMxNjk2MiwicGF0aCI6Ii85Mzk4MDYyMS8zODkxMzEyMzYtMGEwOWIzMzAtYzIxMC00YzQ4LThkNTMtMTk2YmNkNmQ4Y2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDIzMDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NjlmN2I5YzgwZDNhMmMxZDQ0MWI3Yzc5MTJlMzk5NTdlMWU4YjgyODI5ZjQ0NDE3OTcyZGM4YTZlYWE3ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B5klaM_eT6Zk6xRn1FzLh7XHkh2v7eH0ctzDejFfzt0)
> 
> ### Final Comments
> This PR successfully addresses its purpose, but I recommand some changes before merging it. Great work overall!

Hell [...]

2024-11-23 00:12 UTC, NBCCF025 approved these changes
It is all good now, this PR is approved.

But you said that I missunderstood the logic with the `isOfflineState`. However, you removed the duplicate from the GoogleSignInButton to only let the one in the onAuthComplete. And this was what I meant by the change to do.

2024-11-23 00:12 UTC, NBCCF025 commented on app/src/androidTest/java/com/github/se/signify/ui/screens/home/FeedbackScreenTest.kt
We should have a `setUp()` function for the `setContent` on this file test, but as it is not related to the change done in this PR, we can let it like that.

2024-11-23 00:13 UTC, merged