Cleanup `Utils.kt`
Signify-epfl/signify-app pull request #328
Opened 2024-12-06 00:33 UTC by ThomasMPont

2024-12-06 02:16 UTC, ThomasMPont commented
Thanks for being addressing all my code comments so clearly.
I couldn't find any mention of unauthenticated mode functionality though. Are you also planning to address this next sprint?

2024-12-06 11:02 UTC, ThomasMPont commented
I've marked this as a draft while I implement some of the coaches feedback.

2024-12-08 20:49 UTC, NBCCF025 requested changes
## Changes
In this PR, you address long-standing issues with the Utils.kt file by reorganizing its content, improving consistency, and ensuring better developer usability. The changes are well-documented, with thoughtful renames, deletions, and reorganizations.
You also fix the ASLRecognition to use the `AnnexScaffoldScreen` instead of the `MainScaffoldScreen`. Great job!

## Requested changes
I have requested a couple changes in code comments and some of them concern sonar cloud issues. I know that you didn't worked on the `Language`, but with the reorganizations you have done, already existing code raise issues.

2024-12-08 21:45 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/screens/home/ASLRecognition.kt
> +    Column(modifier = Modifier.fillMaxSize(), horizontalAlignment = Alignment.CenterHorizontally) {
Fixed.

2024-12-08 21:51 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreen.kt
>  @SuppressLint("UnusedMaterialScaffoldPaddingParameter")
I didn't change this file beyond automatic import changes from moving functions around. So I won't fix this in this PR, on principle.

2024-12-08 21:51 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt
>  @SuppressLint("UnusedMaterialScaffoldPaddingParameter")
Again, this is not related to my changes.

2024-12-08 21:52 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeScreen.kt
>  @SuppressLint("UnusedMaterialScaffoldPaddingParameter")
Again, this is not related to my changes.

2024-12-08 21:57 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/common/Statistics.kt
> +@VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
This annotation is the best way I've found of making functions essentially private without breaking their tests. It throws a warning whenever the function is used elsewhere.
I believe this should've been used all over the codebase to stop developers from using unintended elements such as the `TopBar` which should never be used outside of `common/Screens.kt`.

I mention this decision in my description.

2024-12-08 21:57 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/common/Screens.kt
> +@VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
Same as above.

2024-12-08 21:57 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/common/Screens.kt
> +@VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
Same as above.

2024-12-08 21:57 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/common/Screens.kt
> +@VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
Same as above.

2024-12-08 21:57 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/common/Screens.kt
> +@VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
Same as above.

2024-12-08 22:00 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/common/NotImplementedYet.kt
I don't see why it would need to be deleted, we just won't be using the element in the final app.

2024-12-08 22:07 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/common/Buttons.kt
> +    modifier: Modifier = Modifier,
Nice catch! Fixed.

2024-12-08 22:08 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/common/Buttons.kt
> +    modifier: Modifier = Modifier,
Fixed.

2024-12-08 22:35 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/ui/common/Buttons.kt
> +    testTag: String = "",
You're completely right. I should have stuck to never using `@Suppress`es. I've changed it so that test tags are passed with the modifier now.

2024-12-08 22:37 UTC, ThomasMPont commented on app/src/androidTest/java/com/github/se/signify/ui/screens/home/ASLRecognitionTest.kt
This button is already tested by `common/ScreensTest.kt`. I believe it shouldn't be tested in other screens, since `Screens.kt` should be free to change it's elements at any time without breaking other tests.

2024-12-08 22:39 UTC, ThomasMPont commented on app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChallengeScreenTest.kt
Same idea as above.

2024-12-08 22:39 UTC, ThomasMPont commented on app/src/androidTest/java/com/github/se/signify/ui/common/NotImplementedYetTest.kt
Again, It doesn't hurt to keep this around.

2024-12-08 22:43 UTC, ThomasMPont commented on app/src/androidTest/java/com/github/se/signify/ui/common/ScreensTest.kt
> +    composeTestRule.onNodeWithTag("BackButton").assertHasClickAction()
Nice catch! I had already fixed this in two other places. Let's hope there aren't more of these.

2024-12-08 22:46 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/model/Utils.kt
> +  if (!listOf("en", "fr").contains(languageCode)) {
This was added in a merge after my PR was opened. Thanks for pointing it out.
It's a shame I have to fix this right after it got merged.

2024-12-08 22:49 UTC, ThomasMPont commented on app/src/main/java/com/github/se/signify/model/Utils.kt
> +  if (!listOf("en", "fr").contains(languageCode)) {
Other warnings about deprecation have been added in the same function. I don't care enough to try to fix them. If they were approved, I guess they're safe...

2024-12-08 22:54 UTC, ThomasMPont commented
Good job on catching so many mistakes. It must have been a pain to find where changes were actually made.

2024-12-08 22:58 UTC, ThomasMPont commented
@NBCCF025 
I believe I have addressed all your requests. Could you have a quick look?

2024-12-09 09:43 UTC, NBCCF025 approved these changes
All the requested changes were addressed as needed, and you also gave me explanations. I approve this PR now and will merge it, but we should create tasks for the issues that are already in the code base. Good job!

2024-12-09 09:43 UTC, merged