Sprint Mode
Signify-epfl/signify-app pull request #451
Opened 2024-12-18 17:36 UTC by samymessouak

### **Description**  
This PR introduces a **Sprint Mode** in the challenge feature, where two players compete in a **Best of 3 (BO3)** format. The goal of this mode is for players to input as many words as possible within **1 minute per round**. The winner is determined based on the total number of words completed across all three rounds.  

**Key Features:**  
1. **Sprint Challenge Gameplay**:  
   - Each round lasts for 1 minute.  
   - The player who completes the most words after 3 rounds wins the challenge.  

2. **Automatic Challenge Cleanup**:  
   - Once the second player completes their rounds, the challenge is automatically removed from the **ongoing challenges**.  
   - Results are accessible in the **History Screen** for both players.  

3. **Database Updates**:  
   - Added two new fields to the `challenge` collection to track each player's results:  
     - `player1WordsCompleted`  
     - `player2WordsCompleted`  

4. **Navigation**:  
   - Added a route to navigate to the **Sprint Mode** screen.  

---

### **Testing**  
- Verified the functionality of the Sprint Mode rounds and result calculation.  
- Ensured navigation to Sprint Mode works as expected.  
- Confirmed challenges are deleted from the ongoing challenges after completion and appear correctly in the History Screen.

---

### **Screenshots**  
![image](https://github.com/user-attachments/assets/fb1ca997-7fce-4535-98f2-c6c12a1b9e0c)

---

2024-12-18 22:14 UTC, ziyadbagh requested changes
Review my comments where I’ve suggested some changes, and let me know your thoughts.

2024-12-18 22:14 UTC, ziyadbagh commented on app/src/main/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreen.kt
- The logic for modifying player1RoundCompleted and player2RoundCompleted in updateSprintChallenge is nearly identical and can be extracted into a helper function.
- Values like 60 for timeLeft, "completed", "in_progress", and "Loading challenge..." should be defined as constants to improve maintainability.
- Error cases (onFailure in challengeRepository.updateChallenge) are left unhandled.

2024-12-19 14:40 UTC, samymessouak commented on app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreenTest.kt
> +            mode = "CHRONO",
Done

2024-12-19 14:40 UTC, samymessouak commented on app/src/androidTest/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreenTest.kt
Thank you

2024-12-19 14:40 UTC, samymessouak commented on app/src/main/java/com/github/se/signify/MainActivity.kt
The argument is not mandatory as it is by default to null

2024-12-19 14:40 UTC, samymessouak commented on app/src/main/java/com/github/se/signify/ui/screens/challenge/NewChallengeScreen.kt
Done.

2024-12-19 14:41 UTC, samymessouak commented on app/src/main/java/com/github/se/signify/ui/screens/challenge/ChallengeHistoryScreen.kt
Seems way better for clarity, thank you for the advice. Done.

2024-12-19 14:55 UTC, samymessouak commented on app/src/main/java/com/github/se/signify/ui/screens/challenge/SprintChallengeGameScreen.kt
Thank you for all of those suggestion, I added them and added some test for the helper functions.

2024-12-19 18:20 UTC, SaFouNaldo approved these changes
As @ziyadbagh has network problems, He asked me to approve for him.

2024-12-19 18:21 UTC, SaFouNaldo approved these changes

2024-12-19 18:22 UTC, merged