Redesign Challenge Screen, Implement Challenge Features, and Improve Test Coverage.
Signify-epfl/signify-app pull request #81
Opened 2024-10-16 22:41 UTC by samymessouak

**Design and UI Modifications:**

_Profile Screen Redesign:_

- Updated the design of the ProfileScreen icons to align with the other screen.

_Bottom Navigation Bar Update:_

- Modified the bottom navigation bar to use icons (homeIcon, battleIcon, and profileIcon) from the drawable folder.
- Changed the background to white with a blue top line (#05A9FB) to match the Figma design.
- Added comprehensive tests to ensure that the navigation bar functions as expected and the icons render correctly.
- Removed outdated sections such as "exercises" and "quest"

**_New Features:_**

_ChallengeScreen Implementation:_

- Implemented the ChallengeScreen with two large square buttons for "Challenge" and "History," each with a new design featuring a blue background and dark gray icons.
- The buttons are properly positioned, and the info button shows a popup describing the challenge feature. The text is now stored in strings.xml for localization.
- NewChallengeScreen & ChallengeHistoryScreen:
- Implemented NewChallengeScreen and ChallengeHistoryScreen, ensuring back navigation works without issues.
- Fixed crashes related to back navigation by ensuring the proper handling of the back stack when moving between screens.

**Utilities and Reusable Components:**

_Modified ReusableTextButton Components:_

- Developed reusable composables for buttons with icons and text to reduce code duplication across multiple screens.
- Added unit tests for these components in the new UtilsTest class to ensure proper rendering, click functionality, and overall behavior.

**Strings and Localization:**

- Moved Hardcoded Text to strings.xml:
_Added the following strings to strings.xml:_
- description_challenge: "Here you can challenge your friends to sign language face-offs."
- graphs_history: "Graphs and statistics for the challenges."

These changes ensure the app is more maintainable and easier to localize in the future.

**Test Coverage Improvements:**

_ChallengeScreen Tests:_

- Implemented tests for the ChallengeScreen to verify the correct rendering and interaction of the square buttons and the info popup.

_Bottom Navigation Bar Tests:_

- Ensured the bottom navigation bar icons are displayed correctly, clickable, and properly navigate between screens.

_UtilsTest for Reusable Components:_

- Added unit tests for the reusable components (ReusableButtonWithIcon and ReusableTextButton) to verify their behavior, including click actions, visual consistency, and accessibility features like content descriptions.

**General Improvements:**

_Fixed Navigation Issues:_

- Resolved issues with back navigation in the NewChallengeScreen and ChallengeHistoryScreen, ensuring users can navigate back to the ChallengeScreen without crashes.
- Code Refactoring and Cleanup

2024-10-16 22:47 UTC, ziyadbagh commented on app/src/androidTest/java/com/github/se/signify/ui/screens/BottomBarNavigationTest.kt
> +          selectedItem = LIST_TOP_LEVEL_DESTINATION.first().route,
Clear and concise test

2024-10-16 22:50 UTC, ziyadbagh commented on app/src/androidTest/java/com/github/se/signify/ui/screens/ChallengeHistoryScreenTest.kt
> +class ChallengeHistoryScreenTest {
Very good test Classe : Testing the display of all the elements in the screen and the behaviour of the back arrow

2024-10-16 22:53 UTC, ziyadbagh commented on app/src/androidTest/java/com/github/se/signify/ui/screens/NewChallengeScreenTest.kt
Very good test class, the comments and the clear test name explain well the expected behaviour

2024-10-16 23:02 UTC, ziyadbagh commented on app/src/androidTest/java/com/github/se/signify/ui/screens/UtilsTest.kt
Same remarks applies to this file: clear and well written tests

2024-10-16 23:05 UTC, ziyadbagh commented on app/src/main/java/com/github/se/signify/MainActivity.kt
Its good that you cleaned the main activity as we have set the SignifyAppPreview as the main entry to our app. Good work

2024-10-16 23:09 UTC, ziyadbagh commented on app/src/main/java/com/github/se/signify/Utils.kt
I really like that you've added more customization options to the buttons, it will definitely improve reusability and maintainability in the future.

2024-10-16 23:11 UTC, ziyadbagh commented on app/src/main/java/com/github/se/signify/ui/navigation/BottomNavigationMenu.kt
looks good to me

2024-10-16 23:17 UTC, ziyadbagh commented on app/src/main/java/com/github/se/signify/ui/screens/ChallengeHistoryScreen.kt
i did a preview and it looks good

2024-10-16 23:20 UTC, ziyadbagh commented on app/src/main/res/values/strings.xml
I love that you've added these strings, especially the clear and engaging description for the challenge feature.

2024-10-16 23:26 UTC, ziyadbagh approved these changes
Very good work congrats !!!
i checked your code coverage and it is very good actually :

![image](https://github.com/user-attachments/assets/9dd7b49e-0b84-4107-9925-ba649a956574)

![image](https://github.com/user-attachments/assets/539bb558-2ce5-421b-8243-3840609ed968)

![image](https://github.com/user-attachments/assets/4d767b8a-53ac-4f12-9acb-7cbc0420f060)

![image](https://github.com/user-attachments/assets/f96442ef-e85d-4788-830a-9a63a0b0282e)

Keep up the good work

2024-10-17 07:44 UTC, ThomasMPont requested changes
With 13% code duplication and 8 new issues on SonarCloud, I can't let this PR be merged.
Please either fix both these problems entirely, or split this PR into a PR for each issue it concerns, as it should have been in the first place.

2024-10-17 08:09 UTC, ThomasMPont requested changes
Gargantuan pull requests like this one makes the review process difficult for everyone, here's why.

## Issues

Why are all these changes in a single PR? Is this necessary?  
You should be submitting a PR for each individual self contained change. If your changes are not self contained, try to make them that.  
This PR is not even linked to an issue, which goes against the basic principle of justifying our changes, we have agreed on. In fact it seems to be related to at least **5** specific tasks. Each task and its linked issue should be getting its own branch and associated PR.
By not having one PR per issue, a reviewer must either accept all your changes or reject them all, which I am currently doing. With multiple issues, maybe some of the changes would have been deemed safe to merge.

## Commits

Why are 5 issues being closed by 1 commit? The commit message isn't descriptive enough to encapsulate all your changes, despite being oven its maximum length.  
Commits should be made as small as possible. Unless changes depend on each other, you should at the very least have one commit per changed file.
Unclear and humongous commits, make for a very difficult time understanding your changes and their reasoning, and pinpointing problematic changes.

## Expected changess

This would be a lot of work to catch up on, but you could save your changes, revert back to main, and create new branches, commits and PRs from the ground up. By committing these changes one by one.

Alternatively, if the other reviewers agree to approve your code, you could keep this PR **as an exception** and fix all the SonarCloud problems on the branch, before we can merge the changes. This is risky, because a single problematic line of code, could invalidate all your work.

2024-10-17 08:25 UTC, NBCCF025 requested changes
### Pull Request: **Profile Screen Redesign, New Features, and UI Enhancements**

#### Review Summary:
This pull request introduces significant UI updates, new screens, reusable components, and improvements in test coverage. The changes are well-rounded, addressing both user experience and code maintainability. However, there are some areas where improvements can further enhance the codebase, particularly in testing and documentation.

#### Positive Aspects:

1. **Bottom Navigation Bar**:
   - The use of icons from the `drawable` folder and the alignment with the Figma design, including the blue top line and white background, are well-executed.
   - Tests for the navigation bar’s functionality (icon rendering and click actions) are a valuable addition to ensure stability.

2. **ChallengeScreen & New Features**:
   - Implementing the **ChallengeScreen** and separating the challenge and history buttons is intuitive. Storing descriptive text in `strings.xml` supports localization and maintainability.
   - Addressing back navigation issues and ensuring smooth transitions between screens (Challenge, NewChallenge, ChallengeHistory) is crucial for a seamless user experience.

3. **Utilities and Reusable Components**:
   - Refactoring and improving the code for reusable components like `ReusableButtonWithIcon` and `ReusableTextButton` is very good. It reduces redundancy and makes future updates easier.
   - Including tests for these components is great for maintaining consistency and ensuring behavior across screens. The focus on both functionality (e.g., click actions) and accessibility (e.g., content descriptions) is commendable.

4. **Strings**:
   - Moving hardcoded text to `strings.xml` demonstrates a clear focus on best practices. It makes the app more maintainable.

5. **Test Coverage Improvements**:
   - The effort to ensure comprehensive test coverage for new features (e.g., ChallengeScreen, navigation bar, and reusable components) is valuable. Tests for both rendering and interaction provide robust checks against regression.

---

### Mandatory Improvements:

1. **Too Much Parameters**:
   - Two function have more than 7 parameters, that can be addressed by using list to merge some of them that are similar.
   - "src/main/java/com/github/se/signify/Utils.kt", the function ReusableTextButton has 8 parameters.
   - "src/main/java/com/github/se/signify/ui/screens/ChallengeScreen.kt", the function SquareButton has 10 parameters.

2. **Unused Import**:
   - Remove the unused import from the file "src/main/java/com/github/se/signify/ui/screens/ChallengeHistoryScreen.kt"

3. **Choose between material and material3 import library**:
   - In the file "src/main/java/com/github/se/signify/ui/screens/ChallengeHistoryScreen.kt"
   - In the file "src/main/java/com/github/se/signify/ui/screens/NewChallengeScreen.kt"

4. **Code duplication**:
   - Some code duplication occurs when creating column and other UI elements. A suggestion, would be to have more of the basics in the "Utils.kt".

#### Suggested Improvements:

1. **Color Consistency**:
   - Instead of hard coded color, you can use the value in app/src/main/java/com/github/se/signify/ui/theme/Color.kt.
   - It could be great if the actual main screen (The screen where the user is located) has the logo in blue (#05A9FB) instead of the gray (#333333), like in the Figma (this could be a task for next sprint).

---

### General Recommendations and summary:
This pull request does a great job improving the app both from a design perspective and in terms of maintainability. The improvement of reusable components, refactoring, and increased test coverage all contribute to a more robust codebase. However, the issues flagged by SonarCloud should be addressed before this pull request can be accepted and merged.

2024-10-17 10:24 UTC, SaFouNaldo approved these changes
Hello,
In my opinion :  after I tested your work in my machine everything works as intended and that's great. 
There are requirements that are not satisfied by Sonar, which is still in development.
For now and for me as a developer that's a valid implementation.

Future work would be to clean up the code.

--> Approved

2024-10-17 10:38 UTC, merged